### ISSUE TITLE
NullReferenceException when creating Topic without TopicConfig (version 0.9.2 pre-release)

### ISSUE THREAD

**Issue by thethomp** [ah-/rdkafka-dotnet#96]
I installed `RdKafka 0.9.2-ci-181` and `RdKafka.Internal.librdkafka 0.9.2-ci-28` as I was hitting a bug in 0.9.1 that was blocking me. Once I made the switch to the pre-release libraries, I started hitting this exception. As far as I can tell, the TopicConfig is still defaulted to null in the Topic constructor, which worked fine before, but will now throw exception unless you create an empty TopicConfig and pass that in. Is this by design? If so, all of the example code will need to be updated as it does not run as-is for the new 0.9.2 libraries.

A NullReferenceException is thrown at this line:
`using (Topic topic = producer.Topic(topicName))`

StackTrace:
```System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=RdKafka
  StackTrace:
       at RdKafka.Producer.Topic(String topic, TopicConfig config)
       at SimpleProducer092Test.Program.Main(String[] args) in c:\users\miket\documents\visual studio 2015\Projects\SimpleProducer092Test\SimpleProducer092Test\Program.cs:line 18
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

You can repro by using the SimpleProducer example:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using RdKafka;

namespace SimpleProducer092Test
{
    class Program
    {
        static void Main(string[] args)
        {
            string brokerList = "broker1:9092,broker2:9092,broker3:9092";
            string topicName = "test092topic1";

            using (Producer producer = new Producer(brokerList))
            using (Topic topic = producer.Topic(topicName))
            {
                Console.WriteLine($"{producer.Name} producing on {topic.Name}. q to exit.");

                string text;
                while ((text = Console.ReadLine()) != "q")
                {
                    byte[] data = Encoding.UTF8.GetBytes(text);
                    Task<DeliveryReport> deliveryReport = topic.Produce(data);
                    var unused = deliveryReport.ContinueWith(task =>
                    {
                        Console.WriteLine($"Partition: {task.Result.Partition}, Offset: {task.Result.Offset}");
                    });
                }
            }
        }
    }
}
```

You can work around the issue by creating a TopicConfig object and passing it into the constructor:
```
TopicConfig tc = new TopicConfig();

            using (Producer producer = new Producer(brokerList))
            using (Topic topic = producer.Topic(topicName, tc))
            {
```

**Comment by treziac** [comment]
My bad, forgot a commit in last PR. Either use previous prerelease or wait for Andreas to merge
